# Generated by Django 3.0.5 on 2020-04-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200410_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.IntegerField(),
        ),
    ]
